# Generated by Django 3.2.20 on 2023-08-25 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='feature_img',
            field=models.ImageField(blank=True, null=True, upload_to='post/feture'),
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnail_img',
            field=models.ImageField(blank=True, null=True, upload_to='post/thumbnail'),
        ),
    ]
