# Generated by Django 3.2.20 on 2023-09-01 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_comment_comment_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_author',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='commenter_name',
            new_name='user',
        ),
    ]
