# Generated by Django 3.2.20 on 2023-09-04 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_user_phone_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_img',
            field=models.ImageField(blank=True, null=True, upload_to='UserImg'),
        ),
    ]
